---
- name: Set timezone to Asia/Tokyo
  ansible.builtin.timezone:
    name: Asia/Tokyo

- name: Check common_locale
  ansible.builtin.command: localectl status
  register: common_localectl_result
  check_mode: false
  changed_when: false

- name: Change common_locale
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
  when: "'LANG=en_US.UTF-8' not in common_localectl_result.stdout"
  changed_when: true
